# Default values for go-web-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: "18757326797"
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 80



